### ISSUE TITLE
Feature request: no final name

### ISSUE THREAD

**Issue by Cammagno** [jdeal/obsidian-path-title-plugin#1]
It could be nice to have an option to not show at the end of the path the name of the note, that is already shown as the note title.

Edit: I just realized that it only happens for Folder Notes

**Comment by jdeal** [comment]
I was going to ask you what a "folder note" was, but it looks like it's from a plugin? Looks like there are a couple, which one are you using? 

If you have a fixed set of folders you want to hide, you could create a replacement like this (where YourFolderName is the folder you want to hide):

```
Replacement Type: Regular Expression in Path
Matching Regular Expression: (/|^)YourFolderName$
Replacement Text:
```

Because the replacement text is empty, it will replace that folder (only at the end of the path) with nothing.
