### ISSUE TITLE
Play nicely with Sliding Panes

### ISSUE THREAD

**Issue by richardOracleDba** [jdeal/obsidian-path-title-plugin#4]
Hi,

Great plugin, I find it really useful.

However, when used in combination with the sliding panes plugin it does have an issue.   The vertical bar that you place between the path and the note name is still vertical when using the sliding panes plugin.  This causes the path to have a line through it which makes it hard to read.

Could you add an option so that we can specify whether the bar is vertical or horizontal, then we can make the adjustment ourselves, assuming you cannot automatically detect whether the note title is being displayed in horizontal or vertical format.

Thanks for the effort you have made in creating this plugin, I know it takes time.

Regards,
Richard

**Comment by jdeal** [comment]
Hey @richardOracleDba,

Thanks for letting me know about this. I _think_ I've fixed this with the latest release (1.0.7).

It detects if there's a vertical text orientation and then changes some styling to make it look right.

Note that if you turn on/off the Sliding Panes plugin with any panes open, you have to also do one of the following:

- Toggle Path Title plugin off and on.
- Close all open panes and reopen them.

Otherwise, any open panes will have the styling for the previous text orientation.

Justin
